# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Objects.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Objects.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rObjects.proto\"\'\n\x0bObjectsList\x12\x18\n\x07objects\x18\x01 \x03(\x0b\x32\x07.Object\"\xc2\x01\n\x06Object\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\n\n\x02id\x18\x04 \x01(\t\x12\x17\n\x05light\x18\x05 \x01(\x0b\x32\x06.LightH\x00\x12\x11\n\x02tv\x18\x06 \x01(\x0b\x32\x03.TvH\x00\x12/\n\x11temperaturesensor\x18\x07 \x01(\x0b\x32\x12.TemperatureSensorH\x00\x12\x1b\n\x07\x66reezer\x18\x08 \x01(\x0b\x32\x08.FreezerH\x00\x42\x08\n\x06object\"$\n\x05Light\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\t\"%\n\x02Tv\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0e\n\x06volume\x18\x02 \x01(\x05\"(\n\x11TemperatureSensor\x12\x13\n\x0btemperature\x18\x01 \x01(\x05\"<\n\x07\x46reezer\x12\x13\n\x0btemperature\x18\x01 \x01(\x05\x12\x1c\n\x05power\x18\x02 \x01(\x0e\x32\r.FreezerPower*-\n\x0c\x46reezerPower\x12\x07\n\x03LOW\x10\x00\x12\n\n\x06MEDIUM\x10\x01\x12\x08\n\x04HIGH\x10\x02\x62\x06proto3'
)

_FREEZERPOWER = _descriptor.EnumDescriptor(
  name='FreezerPower',
  full_name='FreezerPower',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOW', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=436,
  serialized_end=481,
)
_sym_db.RegisterEnumDescriptor(_FREEZERPOWER)

FreezerPower = enum_type_wrapper.EnumTypeWrapper(_FREEZERPOWER)
LOW = 0
MEDIUM = 1
HIGH = 2



_OBJECTSLIST = _descriptor.Descriptor(
  name='ObjectsList',
  full_name='ObjectsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='objects', full_name='ObjectsList.objects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=56,
)


_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Object.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='Object.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='Object.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='Object.id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='light', full_name='Object.light', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tv', full_name='Object.tv', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperaturesensor', full_name='Object.temperaturesensor', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='freezer', full_name='Object.freezer', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='object', full_name='Object.object',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=59,
  serialized_end=253,
)


_LIGHT = _descriptor.Descriptor(
  name='Light',
  full_name='Light',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Light.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='Light.color', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=291,
)


_TV = _descriptor.Descriptor(
  name='Tv',
  full_name='Tv',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='Tv.channel', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume', full_name='Tv.volume', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=330,
)


_TEMPERATURESENSOR = _descriptor.Descriptor(
  name='TemperatureSensor',
  full_name='TemperatureSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='TemperatureSensor.temperature', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=372,
)


_FREEZER = _descriptor.Descriptor(
  name='Freezer',
  full_name='Freezer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='Freezer.temperature', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='power', full_name='Freezer.power', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=434,
)

_OBJECTSLIST.fields_by_name['objects'].message_type = _OBJECT
_OBJECT.fields_by_name['light'].message_type = _LIGHT
_OBJECT.fields_by_name['tv'].message_type = _TV
_OBJECT.fields_by_name['temperaturesensor'].message_type = _TEMPERATURESENSOR
_OBJECT.fields_by_name['freezer'].message_type = _FREEZER
_OBJECT.oneofs_by_name['object'].fields.append(
  _OBJECT.fields_by_name['light'])
_OBJECT.fields_by_name['light'].containing_oneof = _OBJECT.oneofs_by_name['object']
_OBJECT.oneofs_by_name['object'].fields.append(
  _OBJECT.fields_by_name['tv'])
_OBJECT.fields_by_name['tv'].containing_oneof = _OBJECT.oneofs_by_name['object']
_OBJECT.oneofs_by_name['object'].fields.append(
  _OBJECT.fields_by_name['temperaturesensor'])
_OBJECT.fields_by_name['temperaturesensor'].containing_oneof = _OBJECT.oneofs_by_name['object']
_OBJECT.oneofs_by_name['object'].fields.append(
  _OBJECT.fields_by_name['freezer'])
_OBJECT.fields_by_name['freezer'].containing_oneof = _OBJECT.oneofs_by_name['object']
_FREEZER.fields_by_name['power'].enum_type = _FREEZERPOWER
DESCRIPTOR.message_types_by_name['ObjectsList'] = _OBJECTSLIST
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['Light'] = _LIGHT
DESCRIPTOR.message_types_by_name['Tv'] = _TV
DESCRIPTOR.message_types_by_name['TemperatureSensor'] = _TEMPERATURESENSOR
DESCRIPTOR.message_types_by_name['Freezer'] = _FREEZER
DESCRIPTOR.enum_types_by_name['FreezerPower'] = _FREEZERPOWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObjectsList = _reflection.GeneratedProtocolMessageType('ObjectsList', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTSLIST,
  '__module__' : 'Objects_pb2'
  # @@protoc_insertion_point(class_scope:ObjectsList)
  })
_sym_db.RegisterMessage(ObjectsList)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT,
  '__module__' : 'Objects_pb2'
  # @@protoc_insertion_point(class_scope:Object)
  })
_sym_db.RegisterMessage(Object)

Light = _reflection.GeneratedProtocolMessageType('Light', (_message.Message,), {
  'DESCRIPTOR' : _LIGHT,
  '__module__' : 'Objects_pb2'
  # @@protoc_insertion_point(class_scope:Light)
  })
_sym_db.RegisterMessage(Light)

Tv = _reflection.GeneratedProtocolMessageType('Tv', (_message.Message,), {
  'DESCRIPTOR' : _TV,
  '__module__' : 'Objects_pb2'
  # @@protoc_insertion_point(class_scope:Tv)
  })
_sym_db.RegisterMessage(Tv)

TemperatureSensor = _reflection.GeneratedProtocolMessageType('TemperatureSensor', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATURESENSOR,
  '__module__' : 'Objects_pb2'
  # @@protoc_insertion_point(class_scope:TemperatureSensor)
  })
_sym_db.RegisterMessage(TemperatureSensor)

Freezer = _reflection.GeneratedProtocolMessageType('Freezer', (_message.Message,), {
  'DESCRIPTOR' : _FREEZER,
  '__module__' : 'Objects_pb2'
  # @@protoc_insertion_point(class_scope:Freezer)
  })
_sym_db.RegisterMessage(Freezer)


# @@protoc_insertion_point(module_scope)
