# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devices.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rDevices.proto\"%\n\x12\x44\x65viceUpdateStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\"&\n\nDeviceList\x12\x18\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x07.Device\"\xdf\x02\n\x06\x44\x65vice\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\n\n\x02id\x18\x04 \x01(\x05\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\x17\n\x05light\x18\x06 \x01(\x0b\x32\x06.LightH\x00\x12)\n\x0epresencesensor\x18\x07 \x01(\x0b\x32\x0f.PresenceSensorH\x00\x12)\n\x0e\x61irconditioner\x18\x08 \x01(\x0b\x32\x0f.AirConditionerH\x00\x12\x19\n\x06heater\x18\t \x01(\x0b\x32\x07.HeaterH\x00\x12/\n\x11temperaturesensor\x18\n \x01(\x0b\x32\x12.TemperatureSensorH\x00\x12\'\n\rfiresupressor\x18\x0b \x01(\x0b\x32\x0e.FireSupressorH\x00\x12#\n\x0bsmokesensor\x18\x0c \x01(\x0b\x32\x0c.SmokeSensorH\x00\x42\x08\n\x06\x64\x65vice\"(\n\x05Light\x12\x10\n\x08location\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\t\"\"\n\x0ePresenceSensor\x12\x10\n\x08location\x18\x01 \x01(\t\"%\n\x0e\x41irConditioner\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\"\x1d\n\x06Heater\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\"(\n\x11TemperatureSensor\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\"!\n\rFireSupressor\x12\x10\n\x08location\x18\x01 \x01(\t\"\x1f\n\x0bSmokeSensor\x12\x10\n\x08location\x18\x01 \x01(\t2>\n\x0c\x44\x65viceUpdate\x12.\n\x0cUpdateDevice\x12\x07.Device\x1a\x13.DeviceUpdateStatus\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Devices_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICEUPDATESTATUS._serialized_start=17
  _DEVICEUPDATESTATUS._serialized_end=54
  _DEVICELIST._serialized_start=56
  _DEVICELIST._serialized_end=94
  _DEVICE._serialized_start=97
  _DEVICE._serialized_end=448
  _LIGHT._serialized_start=450
  _LIGHT._serialized_end=490
  _PRESENCESENSOR._serialized_start=492
  _PRESENCESENSOR._serialized_end=526
  _AIRCONDITIONER._serialized_start=528
  _AIRCONDITIONER._serialized_end=565
  _HEATER._serialized_start=567
  _HEATER._serialized_end=596
  _TEMPERATURESENSOR._serialized_start=598
  _TEMPERATURESENSOR._serialized_end=638
  _FIRESUPRESSOR._serialized_start=640
  _FIRESUPRESSOR._serialized_end=673
  _SMOKESENSOR._serialized_start=675
  _SMOKESENSOR._serialized_end=706
  _DEVICEUPDATE._serialized_start=708
  _DEVICEUPDATE._serialized_end=770
# @@protoc_insertion_point(module_scope)
