# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.Devices_pb2 as Devices__pb2


class DeviceUpdateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateDevice = channel.unary_unary(
                '/DeviceUpdate/UpdateDevice',
                request_serializer=Devices__pb2.Device.SerializeToString,
                response_deserializer=Devices__pb2.DeviceUpdateStatus.FromString,
                )


class DeviceUpdateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceUpdateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDevice,
                    request_deserializer=Devices__pb2.Device.FromString,
                    response_serializer=Devices__pb2.DeviceUpdateStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeviceUpdate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeviceUpdate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DeviceUpdate/UpdateDevice',
            Devices__pb2.Device.SerializeToString,
            Devices__pb2.DeviceUpdateStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
